---
- hosts: dbservers
  remote_user: ansible-control
  gather_facts: true
  become: true
  roles:
    - base

- hosts: dbservers
  remote_user: ansible-control
  gather_facts: true
  become: true
  vars_files:
      - vars/main.yaml
  roles:
      - geerlingguy.mysql

- hosts: dbservers
  remote_user: ansible-control
  gather_facts: true
  become: true
  tasks:
    - name: expose port 3306
      shell: firewall-cmd --zone=public --add-port=3306/tcp

