---
- hosts: dbservers
  remote_user: ansible-control
  gather_facts: true
  become: true
  roles:
    - base
    
- hosts: dbservers
  remote_user: ansible-control
  gather_facts: true
  become: true
  vars_files:
    - vars/main.yaml
  roles:
    - dbserver



