---

- name: install java role
  include_role:
         name: geerlingguy.java

- name: install maven role
  include_role:
         name: gantsign.maven

- name: install nodejs role
  include_role:
          name: geerlingguy.nodejs

- name: Install packages
  yum:
    name:
      - git
      - mysql
#      - mariadb-connector
    state: present

- name: set enviromental variables
  shell: export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64" && export M2_HOME="/opt/maven/apache-maven-3.8.1" && export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

- name: configure Pharmacy application from git
  import_tasks: ./roles/webserver/tasks/configure-git-project.yaml

- name: run maven project
  shell: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/java -jar ISA-Backend-0.0.1-SNAPSHOT.jar > /home/ansible-control/logs/mvn-run.log 2>&1 &
  args:
    chdir:  /home/ansible-control/pharmacy-app/ISA-Backend/target

- name: run node project
  shell: npm start  > /home/ansible-control/logs/npm-start.log 2>&1 &
  args:
    chdir:  /home/ansible-control/pharmacy-app/ISA-Frontend
